version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - WHAPI_TOKEN=Kgv99AHHRsweYlcI8SGXKo0eKEq2FS14
      - WHAPI_API_URL=https://gate.whapi.cloud/
      - BOT_WEBHOOK_URL=https://rndvh-185-138-186-60.a.free.pinggy.link/hook/messages
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - PORT=5000
      - DEBUG=True
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: